### ISSUE TITLE
Authentication error - Please add refreshToken, even though refresh token is included

### ISSUE THREAD

**Issue by draven72** [googleads/keyword-optimizer#4]
Not sure if this is an issue with the code or me, but I've updated ads.properties with my client secret, client id, developer token and customer ID (which I'm assuming is my MCC) and then created a refresh token in Oauth 2.0 Playground but I get this error:

Using ads properties file: src/main/resources/ads.properties
An error occurred: Authentication error
Exception in thread "main" com.google.api.ads.adwords.keywordoptimizer.KeywordOptimizerException: Authentication error
	at com.google.api.ads.adwords.keywordoptimizer.KeywordOptimizer.createContext(KeywordOptimizer.java:712)
	at com.google.api.ads.adwords.keywordoptimizer.KeywordOptimizer.run(KeywordOptimizer.java:143)
	at com.google.api.ads.adwords.keywordoptimizer.KeywordOptimizer.main(KeywordOptimizer.java:96)
Caused by: com.google.api.ads.common.lib.exception.OAuthException: Please add your refreshToken to your ads.properties file
	at com.google.api.ads.adwords.keywordoptimizer.AdWordsApiUtil.init(AdWordsApiUtil.java:216)
	at com.google.api.ads.adwords.keywordoptimizer.AdWordsApiUtil.<init>(AdWordsApiUtil.java:89)
	at com.google.api.ads.adwords.keywordoptimizer.KeywordOptimizer.createContext(KeywordOptimizer.java:703)
	... 2 more
Caused by: User agent must be set and not be the default [INSERT_USERAGENT_HERE] caused by: [userAgent]
	at com.google.api.ads.adwords.keywordoptimizer.AdWordsApiUtil.getUserAgentFromConfig(AdWordsApiUtil.java:162)
	at com.google.api.ads.adwords.keywordoptimizer.AdWordsApiUtil.init(AdWordsApiUtil.java:200)
	... 4 more

when I run:

java -jar target/keyword-optimizer.jar -ap src/main/resources/ads.properties -kp src/main/resources/keyword-optimizer.properties -stf src/main/resources/keywords.txt -o CSV -of src/main/resources/results.csv -m PHRASE -cpc 5.0

If I edit the refresh token, it throws a 400 error, so I'm guessing that the refresh token is correct.

I've also left the api.adwords.userAgent hashed out, so not sure if this is no longer an optional value.

**Comment by timoboz** [comment]
Looks like the issue is not about the developer token, but rather api.adwords.userAgent, which is indeed not optional. See this line in your stack trace:

Caused by: User agent must be set and not be the default [INSERT_USERAGENT_HERE]

Please simply remove the hash and set an appropriate value for the user agent (can be any string). I will also update the example config to reflect this.
